# Generated by Django 6.0.4 on 2026-04-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('comercial', 'Comercial'), ('terreno', 'Terreno'), ('galpao', 'Galpão')], max_length=20)),
                ('status', models.CharField(choices=[('ocupado', 'Ocupado'), ('vago', 'Vago'), ('manutencao', 'Em Manutenção')], default='vago', max_length=20)),
                ('endereco', models.CharField(max_length=300)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(default='', max_length=100)),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área (m²)')),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['endereco'],
            },
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('profissao', models.CharField(blank=True, max_length=100, verbose_name='Profissão')),
                ('renda_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inquilino',
                'verbose_name_plural': 'Inquilinos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('encerrado', 'Encerrado'), ('rescindido', 'Rescindido')], default='ativo', max_length=20)),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal')),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10, verbose_name='Dia de Vencimento')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Arquivo do Contrato')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='imoveis.imovel')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='imoveis.inquilino')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aluguel', 'Aluguel'), ('condominio', 'Condomínio'), ('iptu', 'IPTU'), ('manutencao', 'Manutenção'), ('multa', 'Multa'), ('outros', 'Outros')], max_length=20)),
                ('status', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('atrasado', 'Atrasado')], default='pendente', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='imoveis.contrato')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='LaudoVistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Vistoria de Entrada'), ('saida', 'Vistoria de Saída'), ('periodica', 'Vistoria Periódica')], max_length=20)),
                ('data', models.DateField()),
                ('responsavel', models.CharField(max_length=200, verbose_name='Responsável pela Vistoria')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='laudos/', verbose_name='Laudo em PDF')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laudos', to='imoveis.contrato')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudos', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Laudo de Vistoria',
                'verbose_name_plural': 'Laudos de Vistoria',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imoveis', to='imoveis.proprietario'),
        ),
    ]
