# Generated by Django 4.2.30 on 2026-04-16 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='comprovante_anual',
            field=models.FileField(blank=True, null=True, upload_to='contratos/comprovante_anual/', verbose_name='Comprovante Anual de Pagamento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='comprovante_renda',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_renda/', verbose_name='Comprovante de Renda (PF)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_social',
            field=models.FileField(blank=True, null=True, upload_to='contratos_sociais/', verbose_name='Contrato Social (PJ)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='recibo_chaves',
            field=models.FileField(blank=True, null=True, upload_to='contratos/recibo_chaves/', verbose_name='Recibo de Entrega de Chaves'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de Contrato'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cadastro_prefeitura',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cadastro Prefeitura'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='car',
            field=models.CharField(blank=True, max_length=100, verbose_name='CAR'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='categoria',
            field=models.CharField(choices=[('urbano', 'Urbano'), ('rural', 'Rural')], default='urbano', max_length=10, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aquisição'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='incra',
            field=models.CharField(blank=True, max_length=50, verbose_name='INCRA'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='matricula',
            field=models.CharField(blank=True, max_length=100, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='nirf',
            field=models.CharField(blank=True, max_length=50, verbose_name='NIRF'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='planta_projeto',
            field=models.FileField(blank=True, null=True, upload_to='plantas/', verbose_name='Planta/Projeto'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_aquisicao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor de Aquisição'),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='qualificacao',
            field=models.CharField(blank=True, help_text='Estado civil, profissão, nacionalidade', max_length=300, verbose_name='Qualificação'),
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tributos', 'Pagamento de Tributos (IPTU/ITR)'), ('reforma', 'Reforma/Adequação'), ('construcao_inicial', 'Construção Inicial'), ('consumos', 'Consumos (água/energia/condom.)'), ('despesas_juridicas', 'Despesas Jurídicas'), ('previsao_despesas', 'Previsão de Despesas')], max_length=30)),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('pago_por', models.CharField(choices=[('inquilino', 'Inquilino'), ('administradora', 'Administradora')], max_length=15, verbose_name='Pago Por')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='saidas/')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RenovacaoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('12_12', '12/12 meses'), ('12_30', '12/30 meses'), ('12_indeterminado', '12/Indeterminado')], max_length=20, verbose_name='Tipo de Renovação')),
                ('data_renovacao', models.DateField(verbose_name='Data da Renovação')),
                ('novo_valor_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Novo Valor Mensal')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='renovacao', to='imoveis.contrato')),
            ],
            options={
                'verbose_name': 'Renovação de Contrato',
                'verbose_name_plural': 'Renovações de Contrato',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('prefeitura', 'Prefeitura'), ('receita_federal', 'Receita Federal'), ('bombeiros', 'Corpo de Bombeiros'), ('outro', 'Outro')], max_length=20)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('data_recebimento', models.DateField(verbose_name='Data de Recebimento')),
                ('data_resposta', models.DateField(blank=True, null=True, verbose_name='Data de Resposta')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='notificacoes/', verbose_name='Documento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('respondida', 'Respondida'), ('arquivada', 'Arquivada')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.CreateModel(
            name='FotoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_imoveis/')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Foto do Imóvel',
                'verbose_name_plural': 'Fotos do Imóvel',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Fiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('qualificacao', models.CharField(blank=True, max_length=300, verbose_name='Qualificação')),
                ('rg_cpf', models.CharField(max_length=20, verbose_name='RG/CPF')),
                ('certidao_onus', models.FileField(blank=True, null=True, upload_to='certidoes/', verbose_name='Certidão de Ônus')),
                ('garantia', models.CharField(blank=True, max_length=200, verbose_name='Garantia')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiadores', to='imoveis.contrato')),
            ],
            options={
                'verbose_name': 'Fiador',
                'verbose_name_plural': 'Fiadores',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recibo_imovel', 'Recibo por Imóvel'), ('recibo_periodo', 'Recibo por Período'), ('previsao_mes', 'Previsão de Recebíveis (Mês)'), ('previsao_ano', 'Previsão de Recebíveis (Ano)')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='entradas/')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Distrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('amigavel', 'Distrato Amigável'), ('judicial', 'Ação Judicial de Cobrança')], max_length=10, verbose_name='Tipo de Distrato')),
                ('data_distrato', models.DateField(verbose_name='Data do Distrato')),
                ('recibo_chaves', models.FileField(blank=True, null=True, upload_to='distratos/recibos/', verbose_name='Recibo de Devolução de Chaves')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distrato', to='imoveis.contrato')),
                ('laudo_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.laudovistoria', verbose_name='Laudo de Vistoria de Saída')),
            ],
            options={
                'verbose_name': 'Distrato',
                'verbose_name_plural': 'Distratos',
            },
        ),
    ]
