# Generated by Django 6.0.6 on 2026-07-05 03:38

import django.db.models.deletion
import imoveis.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_contrato_comprovante_anual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComodoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cômodo (Modelo de Vistoria)',
                'verbose_name_plural': 'Cômodos (Modelo de Vistoria)',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='documento_gerado',
            field=models.FileField(blank=True, null=True, upload_to='contratos/gerados/', verbose_name='Contrato gerado (PDF)'),
        ),
        migrations.AddField(
            model_name='laudovistoria',
            name='data_assinatura',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Assinatura'),
        ),
        migrations.AddField(
            model_name='laudovistoria',
            name='documento_gerado',
            field=models.FileField(blank=True, null=True, upload_to='laudos/gerados/', verbose_name='Laudo gerado (PDF)'),
        ),
        migrations.AddField(
            model_name='laudovistoria',
            name='local_assinatura',
            field=models.CharField(blank=True, max_length=200, verbose_name='Local da Assinatura'),
        ),
        migrations.AlterField(
            model_name='laudovistoria',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laudos', to='imoveis.contrato'),
        ),
        migrations.CreateModel(
            name='ItemVistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comodo', models.CharField(max_length=100, verbose_name='Cômodo')),
                ('item', models.CharField(max_length=150, verbose_name='Item')),
                ('estado', models.CharField(choices=[('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], max_length=10)),
                ('observacao', models.CharField(blank=True, max_length=300, verbose_name='Observação')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='imoveis.laudovistoria')),
            ],
            options={
                'verbose_name': 'Item de Vistoria',
                'verbose_name_plural': 'Itens de Vistoria',
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ItemVistoriaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='imoveis.comodotemplate')),
            ],
            options={
                'verbose_name': 'Item (Modelo de Vistoria)',
                'verbose_name_plural': 'Itens (Modelo de Vistoria)',
                'ordering': ['comodo__ordem', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela_atual', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Parcela Atual')),
                ('parcela_total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total de Parcelas')),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aluguel')),
                ('valor_impostos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Impostos')),
                ('valor_seguros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Seguros')),
                ('valor_condominio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Condomínio')),
                ('quem_pagou', models.CharField(blank=True, max_length=200, verbose_name='Quem Pagou')),
                ('proveniente_sitio', models.CharField(blank=True, help_text='Imóvel de origem do valor. Ex: Apartamento 21C, Prédio Maranhão', max_length=300, verbose_name='Proveniente do Sítio')),
                ('periodo_referente', models.CharField(blank=True, max_length=200, verbose_name='Correspondente ao Período de')),
                ('vencido_em', models.DateField(blank=True, null=True, verbose_name='Vencido em')),
                ('quantia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantia de')),
                ('assinante_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome de Quem Assinou')),
                ('assinante_cpf', models.CharField(blank=True, max_length=14, validators=[imoveis.validators.validate_cpf], verbose_name='CPF de Quem Assinou')),
                ('data_assinatura', models.DateField(blank=True, null=True, verbose_name='Data da Assinatura')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='recibos/', verbose_name='Recibo gerado (PDF)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos', to='imoveis.contrato')),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TestemunhaLaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=14, validators=[imoveis.validators.validate_cpf], verbose_name='CPF')),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testemunhas', to='imoveis.laudovistoria')),
            ],
            options={
                'verbose_name': 'Testemunha do Laudo',
                'verbose_name_plural': 'Testemunhas do Laudo',
            },
        ),
    ]
