# Generated by Django 6.0.6 on 2026-07-05 11:50
# Editada manualmente (Rodada 2 — N1): a RunPython `migrar_renda_para_faixa`
# converte Inquilino.renda_mensal (Decimal) para faixa_renda (choices por
# salário mínimo) ANTES de a coluna renda_mensal ser removida.

from decimal import Decimal

import django.db.models.deletion
import imoveis.validators
from django.db import migrations, models

# Salário mínimo nacional vigente em 2026, usado só para classificar os
# registros existentes nesta migração (irreversível: o valor exato se perde).
SALARIO_MINIMO = Decimal('1631.00')


def migrar_renda_para_faixa(apps, schema_editor):
    Inquilino = apps.get_model('imoveis', 'Inquilino')
    for inquilino in Inquilino.objects.exclude(renda_mensal__isnull=True):
        em_sm = inquilino.renda_mensal / SALARIO_MINIMO
        if em_sm <= 2:
            faixa = 'ate_2sm'
        elif em_sm <= 4:
            faixa = '2_4sm'
        elif em_sm <= 6:
            faixa = '4_6sm'
        elif em_sm <= 10:
            faixa = '6_10sm'
        elif em_sm <= 20:
            faixa = '10_20sm'
        else:
            faixa = 'acima_20sm'
        inquilino.faixa_renda = faixa
        inquilino.save(update_fields=['faixa_renda'])


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_reclassifica_laudo_periodica'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquilino',
            name='faixa_renda',
            field=models.CharField(blank=True, choices=[('ate_2sm', 'Até 2 salários mínimos'), ('2_4sm', 'De 2 a 4 salários mínimos'), ('4_6sm', 'De 4 a 6 salários mínimos'), ('6_10sm', 'De 6 a 10 salários mínimos'), ('10_20sm', 'De 10 a 20 salários mínimos'), ('acima_20sm', 'Acima de 20 salários mínimos')], max_length=20, verbose_name='Faixa de Renda'),
        ),
        migrations.RunPython(migrar_renda_para_faixa, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='saida',
            name='imovel',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='valor_aluguel',
        ),
        migrations.RemoveField(
            model_name='inquilino',
            name='renda_mensal',
        ),
        migrations.RemoveField(
            model_name='proprietario',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='periodo_referente',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='proveniente_sitio',
        ),
        migrations.AddField(
            model_name='imovel',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='recibo',
            name='periodo_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Período — Fim'),
        ),
        migrations.AddField(
            model_name='recibo',
            name='periodo_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Período — Início'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, validators=[imoveis.validators.validate_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[imoveis.validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='rg',
            field=models.CharField(blank=True, max_length=20, validators=[imoveis.validators.validate_rg], verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='laudovistoria',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Vistoria de Entrada'), ('saida', 'Vistoria de Saída')], max_length=20),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='cpf_cnpj',
            field=models.CharField(max_length=20, unique=True, validators=[imoveis.validators.validate_cpf_cnpj], verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='imoveis.contrato'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='imoveis.imovel'),
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.DeleteModel(
            name='Saida',
        ),
    ]
