# Generated by Django 6.0.6 on 2026-07-05 19:05
# Editada manualmente: faixas por salário mínimo trocadas por faixas de renda
# em R$; RunPython remapeia 1:1 (mesma ordem) os registros existentes.

from django.db import migrations, models

MAPA_FAIXA_ANTIGA_PARA_NOVA = {
    'ate_2sm': 'ate_2k',
    '2_4sm': '2_4k',
    '4_6sm': '4_7k',
    '6_10sm': '7_10k',
    '10_20sm': '10_16k',
    'acima_20sm': 'acima_16k',
}


def remapear_faixas(apps, schema_editor):
    Inquilino = apps.get_model('imoveis', 'Inquilino')
    for antiga, nova in MAPA_FAIXA_ANTIGA_PARA_NOVA.items():
        Inquilino.objects.filter(faixa_renda=antiga).update(faixa_renda=nova)


def reverter_faixas(apps, schema_editor):
    Inquilino = apps.get_model('imoveis', 'Inquilino')
    for antiga, nova in MAPA_FAIXA_ANTIGA_PARA_NOVA.items():
        Inquilino.objects.filter(faixa_renda=nova).update(faixa_renda=antiga)


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_remove_saida_imovel_remove_contrato_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='faixa_renda',
            field=models.CharField(blank=True, choices=[('ate_2k', '< R$ 2k'), ('2_4k', 'R$ 2k - R$ 3.9k'), ('4_7k', 'R$ 4k - R$ 6.9k'), ('7_10k', 'R$ 7k - R$ 9.9k'), ('10_16k', 'R$ 10k - R$ 15.9k'), ('acima_16k', 'R$ 16k +')], max_length=20, verbose_name='Faixa de Renda'),
        ),
        migrations.RunPython(remapear_faixas, reverter_faixas),
    ]
