# Generated by Django 6.0.4 on 2026-07-05 20:14

import django.core.validators
import imoveis.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0007_atualiza_faixa_renda_valores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='dia_vencimento',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Vencimento'),
        ),
        migrations.AlterField(
            model_name='fiador',
            name='rg_cpf',
            field=models.CharField(max_length=20, validators=[imoveis.validators.validate_rg_cpf], verbose_name='RG/CPF'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, validators=[imoveis.validators.validate_telefone]),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, validators=[imoveis.validators.validate_telefone]),
        ),
    ]
