# Generated by Django 6.0.6 on 2026-07-06 02:40

import django.db.models.deletion
import imoveis.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0008_alter_contrato_dia_vencimento_alter_fiador_rg_cpf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('laudo', 'Laudo de Vistoria'), ('recibo', 'Recibo')], max_length=10)),
                ('numero_versao', models.PositiveIntegerField(verbose_name='Versão')),
                ('arquivo', models.FileField(upload_to=imoveis.models.documento_gerado_upload_to, verbose_name='Arquivo (PDF)')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('gerado_em', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_gerados', to='imoveis.contrato')),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
                ('laudo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_gerados', to='imoveis.laudovistoria')),
                ('recibo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_gerados', to='imoveis.recibo')),
            ],
            options={
                'verbose_name': 'Documento Gerado (GED)',
                'verbose_name_plural': 'Documentos Gerados (GED)',
                'ordering': ['-gerado_em', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('contrato__isnull', False), ('laudo__isnull', True), ('recibo__isnull', True)), models.Q(('contrato__isnull', True), ('laudo__isnull', False), ('recibo__isnull', True)), models.Q(('contrato__isnull', True), ('laudo__isnull', True), ('recibo__isnull', False)), _connector='OR'), name='documentogerado_origem_unica'), models.UniqueConstraint(condition=models.Q(('contrato__isnull', False)), fields=('contrato', 'numero_versao'), name='documentogerado_versao_unica_contrato'), models.UniqueConstraint(condition=models.Q(('laudo__isnull', False)), fields=('laudo', 'numero_versao'), name='documentogerado_versao_unica_laudo'), models.UniqueConstraint(condition=models.Q(('recibo__isnull', False)), fields=('recibo', 'numero_versao'), name='documentogerado_versao_unica_recibo')],
            },
        ),
    ]
