# Generated by Django 6.0.6 on 2026-07-06 17:59

import imoveis.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0010_documentogerado_retroativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_assinatura',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Assinatura'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='finalidade',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial')], default='residencial', max_length=12, verbose_name='Finalidade'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='local_assinatura',
            field=models.CharField(blank=True, max_length=200, verbose_name='Local da Assinatura'),
        ),
        migrations.AddField(
            model_name='fiador',
            name='conjuge_cpf',
            field=models.CharField(blank=True, max_length=14, validators=[imoveis.validators.validate_cpf], verbose_name='CPF do Cônjuge'),
        ),
        migrations.AddField(
            model_name='fiador',
            name='conjuge_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do Cônjuge'),
        ),
        migrations.AddField(
            model_name='fiador',
            name='conjuge_rg',
            field=models.CharField(blank=True, max_length=20, validators=[imoveis.validators.validate_rg], verbose_name='RG do Cônjuge'),
        ),
        migrations.AddField(
            model_name='fiador',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, validators=[imoveis.validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='fiador',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, verbose_name='Endereço Completo'),
        ),
        migrations.AddField(
            model_name='fiador',
            name='rg',
            field=models.CharField(blank=True, max_length=20, validators=[imoveis.validators.validate_rg], verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='fiador',
            name='qualificacao',
            field=models.CharField(blank=True, help_text='Estado civil, profissão, nacionalidade', max_length=300, verbose_name='Qualificação'),
        ),
    ]
