# Generated by Django 6.0.6 on 2026-07-08 15:52

import django.db.models.deletion
import imoveis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0011_contrato_data_assinatura_contrato_finalidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoItemVistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=imoveis.models.foto_item_vistoria_upload_to)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='imoveis.itemvistoria')),
            ],
            options={
                'verbose_name': 'Foto do Item de Vistoria',
                'verbose_name_plural': 'Fotos do Item de Vistoria',
                'ordering': ['criado_em'],
            },
        ),
    ]
