# Generated by Django 6.0.6 on 2026-07-08 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0012_fotoitemvistoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('nivel', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro'), ('warning', 'Aviso'), ('info', 'Informação')], max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação de Usuário',
                'verbose_name_plural': 'Notificações de Usuário',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
    ]
