# Generated by Django 6.0.6 on 2026-07-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0013_notificacaousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('pode_acessar_dashboard', 'Pode acessar o Dashboard'), ('pode_acessar_financeiro', 'Pode acessar o módulo Financeiro')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
