# Generated by Django 6.0.6 on 2026-07-09 23:29
"""Reversão do GED versionado: DocumentoGerado deixa de existir.

Antes de derrubar o model, apaga fisicamente do storage todo arquivo de
DocumentoGerado que NÃO seja o mesmo referenciado pelo campo legado da
origem (Contrato.documento_gerado / LaudoVistoria.documento_gerado /
Recibo.arquivo). Essa checagem é necessária porque a migration retroativa
0010 criou os registros de numero_versao=1 apontando para o MESMO arquivo
físico do campo legado (sem copiar) — apagar esses cegamente destruiria o
único PDF existente para origens cujo v1 nunca foi regenerado. Só os
arquivos exclusivos da árvore `ged/` (versões geradas depois da 0010, v2+)
são removidos.

Irreversível de propósito: os bytes apagados não podem ser restaurados, então
não há reverse real a oferecer.
"""
from django.db import migrations


def limpar_storage_ged(apps, schema_editor):
    DocumentoGerado = apps.get_model('imoveis', 'DocumentoGerado')

    for doc in DocumentoGerado.objects.all():
        origem = doc.contrato or doc.laudo or doc.recibo
        if origem is None:
            continue
        campo_legado = 'arquivo' if doc.tipo == 'recibo' else 'documento_gerado'
        nome_legado = getattr(origem, campo_legado).name
        if doc.arquivo.name and doc.arquivo.name != nome_legado:
            doc.arquivo.delete(save=False)


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0016_lancamento_ganho_despesa'),
    ]

    operations = [
        migrations.RunPython(limpar_storage_ged, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='documentogerado',
            name='documentogerado_origem_unica',
        ),
        migrations.RemoveConstraint(
            model_name='documentogerado',
            name='documentogerado_versao_unica_contrato',
        ),
        migrations.RemoveConstraint(
            model_name='documentogerado',
            name='documentogerado_versao_unica_laudo',
        ),
        migrations.RemoveConstraint(
            model_name='documentogerado',
            name='documentogerado_versao_unica_recibo',
        ),
        migrations.DeleteModel(
            name='DocumentoGerado',
        ),
    ]
