# Generated by Django 6.0.6 on 2026-07-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0017_remove_documentogerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='valor_vigente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Cobrança Vigente'),
        ),
    ]
