# Generated by Django 6.0.6 on 2026-07-10 01:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0018_contrato_valor_vigente'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoStatusImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ocupado', 'Ocupado'), ('vago', 'Vago'), ('manutencao', 'Em Manutenção')], max_length=20)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início do período')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim do período')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Histórico de Status do Imóvel',
                'verbose_name_plural': 'Históricos de Status do Imóvel',
                'ordering': ['imovel', 'data_inicio'],
            },
        ),
    ]
