# Generated by Django 6.0.6 on 2026-07-10 01:43

from django.db import migrations
from django.utils import timezone


def seed_periodo_atual(apps, schema_editor):
    """Abre um período de status para cada imóvel existente no momento do
    lançamento da feature. Sem retroatividade: a vacância só passa a contar
    a partir daqui. Imóveis criados depois ganham o período pelo signal."""
    Imovel = apps.get_model('imoveis', 'Imovel')
    HistoricoStatusImovel = apps.get_model('imoveis', 'HistoricoStatusImovel')
    agora = timezone.now()
    novos = [
        HistoricoStatusImovel(imovel=imovel, status=imovel.status, data_inicio=agora)
        for imovel in Imovel.objects.all()
    ]
    HistoricoStatusImovel.objects.bulk_create(novos)


def remover_periodos(apps, schema_editor):
    HistoricoStatusImovel = apps.get_model('imoveis', 'HistoricoStatusImovel')
    HistoricoStatusImovel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0019_historicostatusimovel'),
    ]

    operations = [
        migrations.RunPython(seed_periodo_atual, remover_periodos),
    ]
