# Generated by Django 6.0.6 on 2026-07-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0020_seed_historico_status_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_ultimo_reajuste',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Último Reajuste'),
        ),
    ]
