# Generated by Django 6.0.6 on 2026-07-11 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0021_contrato_data_ultimo_reajuste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renovacaocontrato',
            options={'ordering': ['-data_renovacao', '-id'], 'verbose_name': 'Renovação de Contrato', 'verbose_name_plural': 'Renovações de Contrato'},
        ),
        migrations.RemoveField(
            model_name='renovacaocontrato',
            name='novo_valor_mensal',
        ),
        migrations.AlterField(
            model_name='renovacaocontrato',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovacoes', to='imoveis.contrato'),
        ),
    ]
