# Generated by Django 6.0.6 on 2026-07-11 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0022_alter_renovacaocontrato_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='contratos/documentos_pessoais/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='Nome do arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_pessoais', to='imoveis.contrato')),
            ],
            options={
                'verbose_name': 'Documento Pessoal do Contrato',
                'verbose_name_plural': 'Documentos Pessoais do Contrato',
                'ordering': ['criado_em', 'pk'],
            },
        ),
    ]
