# Generated by Django 6.0.6 on 2026-07-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0023_documentocontrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('prefeitura', 'Prefeitura'), ('receita_federal', 'Receita Federal'), ('bombeiros', 'Corpo de Bombeiros'), ('dmae_dme', 'DMAE/DME'), ('outro', 'Outro')], max_length=20),
        ),
    ]
