# Generated by Django 6.0.6 on 2026-07-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0024_alter_notificacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='tipo',
            field=models.CharField(choices=[('aluguel', 'Aluguel'), ('arrendamento', 'Arrendamento'), ('venda', 'Venda'), ('condominio', 'Condomínio'), ('iptu', 'IPTU'), ('manutencao', 'Manutenção'), ('multa', 'Multa'), ('outros', 'Outros')], max_length=20),
        ),
    ]
